services:
  - docker

env:
  - NAME=jat001/archisteamfarm

before_install:
  - VER=$(curl -u "$GITHUB_TOKEN" https://api.github.com/repos/JustArchiNET/ArchiSteamFarm/releases/latest | jq -r '.tag_name')
  - 'curl -f "https://index.docker.io/v1/repositories/$NAME/tags/$VER" && travis_terminate 0 || :'

install:
  - wget --content-disposition "https://github.com/JustArchiNET/ArchiSteamFarm/releases/download/$VER/ASF-linux-x64.zip"
  - unzip ASF-linux-x64.zip -d asf
  - chmod +x asf/ArchiSteamFarm

before_script:
  - docker login -u=jat001 -p="$DOCKER_PASSWD"

script:
  - docker build -t "$NAME:$VER" --build-arg "VER=$VER" .
  - docker tag "$NAME:$VER" "$NAME:latest"

  - docker push "$NAME:$VER"
  - docker push "$NAME:latest"
